# Generated by Django 5.0.3 on 2024-03-11 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationstudent',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='notificationstudent',
            name='student_id',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Notificationstaff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.staffs')),
            ],
        ),
    ]
